# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOrgKuFA_OOshRdM_ShkSvgVvEM01-Ga
"""





# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# import joblib
# import os
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder
# from sklearn.metrics import (
#     accuracy_score, precision_score, recall_score, f1_score,
#     confusion_matrix, roc_auc_score, classification_report
# )
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.preprocessing import StandardScaler
# from imblearn.over_sampling import SMOTE
# 
# st.set_page_config(
#     page_title="Financial Fraud Detection Dashboard",
#     page_icon="💳",
#     layout="wide"
# )
# 
# DATA_PATH = os.path.join(os.path.dirname(__file__), "Bootcamp_project_cleaned.csv")
# 
# @st.cache_data
# def load_data():
#     df = pd.read_csv(DATA_PATH)
#     for col in df.columns:
#         if pd.api.types.is_numeric_dtype(df[col]):
#             df[col] = df[col].fillna(df[col].median())
#         else:
#             df[col] = df[col].fillna("Unknown")
#     return df
# 
# @st.cache_data
# def encode_data(df):
#     categorical_cols = ["Transaction_Type", "Device_Used", "Location", "Payment_Method"]
#     encoders = {}
#     df_encoded = df.copy()
#     for col in categorical_cols:
#         le = LabelEncoder()
#         df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
#         encoders[col] = le
#     return df_encoded, encoders
# 
# df = load_data()
# df_encoded, global_encoders = encode_data(df)
# 
# page = st.sidebar.radio(
#     "Navigation Menu",
#     [
#         "Home Menu",
#         "Data Analysis & Exploration",
#         "Machine Learning Models",
#         "Real-Time Fraud Prediction"
#     ]
# )
# 
# if page == "Home Menu":
#     st.title("💳 Intelligent Financial Fraud Detection System")
# 
#     st.header("💡 Project Concept")
#     st.write("""
#     Building an intelligent system that analyzes the characteristics of financial transactions
#     and determines the probability of them being fraudulent before any final action is taken.
#     This helps financial institutions reduce losses and protect their customers.
#     """)
# 
#     st.header("⚠️ Problem Statement")
#     st.info("""
#     In the current digital age, with the massive expansion of digital payments and e-commerce,
#     financial fraud attempts have significantly increased. Therefore, institutions urgently need
#     solutions capable of detecting suspicious transactions at an early stage.
#     """)
# 
#     st.header("🛠️ Proposed Solution & Objective")
#     st.write("""
#     Developing models based on Machine Learning techniques to analyze financial transactions
#     and predict the likelihood of fraud. These predictions can be utilized to take necessary actions,
#     such as reviewing transactions before approval.
#     """)
# 
#     st.header("🎯 Project Objectives")
#     st.markdown("""
#     - **Analyze financial transaction data** and extract patterns related to fraud.
#     - **Identify the most significant key factors** influencing the detection of suspicious operations.
#     - **Compare the performance of Machine Learning models** in predicting and classifying transactions.
#     - **Develop an interactive dashboard** using Streamlit to simulate the practical deployment of the model.
#     """)
# 
#     st.header("❓ Why Choose This Field?")
#     st.warning("""
#     Financial fraud detection was selected due to people's increasing reliance on electronic payments
#     and banking applications, which has led to a rise in fraud attempts and more sophisticated attack methods.
#     """)
# 
#     st.divider()
# 
#     fraud_cases = int(df["Fraudulent"].sum())
#     safe_cases = int(len(df) - fraud_cases)
#     fraud_pct = (fraud_cases / len(df)) * 100
# 
#     st.subheader("📊 Live Dataset Overview Statistics")
#     col1, col2, col3, col4 = st.columns(4)
#     with col1:
#         st.metric("Total Transactions", f"{len(df):,}")
#     with col2:
#         st.metric("Fraud Cases", f"{fraud_cases:,}", delta=f"{fraud_pct:.2f}% of total", delta_color="inverse")
#     with col3:
#         st.metric("Legitimate Transactions", f"{safe_cases:,}")
#     with col4:
#         raw_df = pd.read_csv(DATA_PATH)
#         st.metric("Missing Cells (Raw)", f"{int(raw_df.isnull().sum().sum()):,}")
# 
#     st.subheader("👀 Dataset Preview (First 10 Rows)")
#     st.dataframe(df.head(10), use_container_width=True)
# 
#     st.subheader("📈 Descriptive Statistics")
#     st.dataframe(df.describe(), use_container_width=True)
# 
# elif page == "Data Analysis & Exploration":
#     st.title("📊 Financial Data Analysis & Exploration")
#     st.write("Visualizing actual patterns, distributions, and behaviors found in the dataset.")
# 
#     rows, cols_count = df.shape
#     raw_df = pd.read_csv(DATA_PATH)
#     missing_total = int(raw_df.isnull().sum().sum())
# 
#     m1, m2, m3 = st.columns(3)
#     with m1:
#         st.metric("Rows (Transactions)", f"{rows:,}")
#     with m2:
#         st.metric("Features (Columns)", cols_count)
#     with m3:
#         st.metric("Missing Cells (Original)", f"{missing_total:,}")
# 
#     st.divider()
# 
#     col_left, col_right = st.columns(2)
# 
#     with col_left:
#         st.subheader("🎯 Fraud vs. Legitimate Distribution")
#         fraud_counts = df["Fraudulent"].value_counts().reset_index()
#         fraud_counts.columns = ["Status", "Count"]
#         fraud_counts["Status"] = fraud_counts["Status"].map({0: "Legitimate", 1: "Fraudulent"})
#         fig1 = px.pie(
#             fraud_counts, names="Status", values="Count",
#             hole=0.45,
#             color="Status",
#             color_discrete_map={"Legitimate": "#2b6cb0", "Fraudulent": "#c53030"}
#         )
#         fig1.update_traces(textposition="inside", textinfo="percent+label")
#         st.plotly_chart(fig1, use_container_width=True)
# 
#     with col_right:
#         st.subheader("💳 Transaction Volume by Type")
#         tx_type = df["Transaction_Type"].value_counts().reset_index()
#         tx_type.columns = ["Transaction Type", "Count"]
#         fig2 = px.bar(
#             tx_type, x="Transaction Type", y="Count",
#             text="Count", color="Count",
#             color_continuous_scale="Blues"
#         )
#         fig2.update_traces(texttemplate="%{text:,}", textposition="outside")
#         st.plotly_chart(fig2, use_container_width=True)
# 
#     st.divider()
#     col_left2, col_right2 = st.columns(2)
# 
#     with col_left2:
#         st.subheader("💰 Transaction Amount Distribution")
#         fig3 = px.histogram(
#             df[df["Transaction_Amount"] < 10000],
#             x="Transaction_Amount", nbins=60,
#             color_discrete_sequence=["#4a90e2"],
#             labels={"Transaction_Amount": "Amount ($)"}
#         )
#         st.plotly_chart(fig3, use_container_width=True)
# 
#     with col_right2:
#         st.subheader("🚨 Fraud Cases by Transaction Type")
#         fraud_by_type = (
#             df.groupby("Transaction_Type")["Fraudulent"]
#             .sum()
#             .reset_index()
#             .sort_values("Fraudulent", ascending=False)
#         )
#         fraud_by_type.columns = ["Transaction Type", "Fraud Cases"]
#         fig4 = px.bar(
#             fraud_by_type, x="Transaction Type", y="Fraud Cases",
#             text="Fraud Cases", color="Fraud Cases",
#             color_continuous_scale="Reds"
#         )
#         fig4.update_traces(texttemplate="%{text:,}", textposition="outside")
#         st.plotly_chart(fig4, use_container_width=True)
# 
#     st.divider()
#     col_left3, col_right3 = st.columns(2)
# 
#     with col_left3:
#         st.subheader("📱 Fraud by Device Used")
#         fraud_by_device = (
#             df.groupby("Device_Used")["Fraudulent"]
#             .agg(["sum", "count"])
#             .reset_index()
#         )
#         fraud_by_device.columns = ["Device", "Fraud Cases", "Total"]
#         fraud_by_device["Fraud Rate (%)"] = (fraud_by_device["Fraud Cases"] / fraud_by_device["Total"] * 100).round(2)
#         fig5 = px.bar(
#             fraud_by_device, x="Device", y="Fraud Rate (%)",
#             text="Fraud Rate (%)", color="Fraud Rate (%)",
#             color_continuous_scale="Oranges"
#         )
#         fig5.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
#         st.plotly_chart(fig5, use_container_width=True)
# 
#     with col_right3:
#         st.subheader("🌍 Fraud Cases by Location")
#         fraud_by_loc = (
#             df.groupby("Location")["Fraudulent"]
#             .sum()
#             .reset_index()
#             .sort_values("Fraudulent", ascending=True)
#         )
#         fraud_by_loc.columns = ["Location", "Fraud Cases"]
#         fig6 = px.bar(
#             fraud_by_loc, x="Fraud Cases", y="Location",
#             orientation="h", color="Fraud Cases",
#             color_continuous_scale="Purples",
#             text="Fraud Cases"
#         )
#         fig6.update_traces(texttemplate="%{text:,}", textposition="outside")
#         st.plotly_chart(fig6, use_container_width=True)
# 
#     st.divider()
#     col_left4, col_right4 = st.columns(2)
# 
#     with col_left4:
#         st.subheader("🕐 Fraud Cases by Hour of Day")
#         fraud_by_hour = (
#             df.groupby("Time_of_Transaction")["Fraudulent"]
#             .sum()
#             .reset_index()
#         )
#         fraud_by_hour.columns = ["Hour", "Fraud Cases"]
#         fig7 = px.line(
#             fraud_by_hour, x="Hour", y="Fraud Cases",
#             markers=True, color_discrete_sequence=["#e53e3e"],
#             labels={"Hour": "Hour of Day (0-23)", "Fraud Cases": "Fraud Count"}
#         )
#         fig7.update_layout(xaxis=dict(tickmode="linear", dtick=1))
#         st.plotly_chart(fig7, use_container_width=True)
# 
#     with col_right4:
#         st.subheader("💳 Fraud by Payment Method")
#         fraud_by_pay = (
#             df.groupby("Payment_Method")["Fraudulent"]
#             .agg(["sum", "count"])
#             .reset_index()
#         )
#         fraud_by_pay.columns = ["Payment Method", "Fraud Cases", "Total"]
#         fraud_by_pay["Fraud Rate (%)"] = (fraud_by_pay["Fraud Cases"] / fraud_by_pay["Total"] * 100).round(2)
#         fig8 = px.bar(
#             fraud_by_pay, x="Payment Method", y="Fraud Rate (%)",
#             text="Fraud Rate (%)", color="Fraud Rate (%)",
#             color_continuous_scale="Teal"
#         )
#         fig8.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
#         st.plotly_chart(fig8, use_container_width=True)
# 
#     st.divider()
# 
#     st.subheader("🔗 Correlation Heatmap (Numeric Features)")
#     numeric_df = df[["Transaction_Amount", "Time_of_Transaction",
#                       "Previous_Fraudulent_Transactions", "Account_Age",
#                       "Number_of_Transactions_Last_24H", "Fraudulent"]]
#     corr = numeric_df.corr()
#     fig_corr = px.imshow(
#         corr, text_auto=".2f", aspect="auto",
#         color_continuous_scale="RdBu_r", zmin=-1, zmax=1,
#         title="Pearson Correlation Matrix"
#     )
#     st.plotly_chart(fig_corr, use_container_width=True)
# 
#     st.divider()
#     st.subheader("📦 Transaction Amount: Fraud vs. Legitimate")
#     df_plot = df[df["Transaction_Amount"] < 10000].copy()
#     df_plot["Status"] = df_plot["Fraudulent"].map({0: "Legitimate", 1: "Fraudulent"})
#     fig_box = px.box(
#         df_plot, x="Status", y="Transaction_Amount",
#         color="Status",
#         color_discrete_map={"Legitimate": "#2b6cb0", "Fraudulent": "#c53030"},
#         points="outliers"
#     )
#     st.plotly_chart(fig_box, use_container_width=True)
# 
#     st.subheader("📊 Previous Fraudulent Transactions vs Fraud Label")
#     pivot = (
#         df.groupby(["Previous_Fraudulent_Transactions", "Fraudulent"])
#         .size()
#         .reset_index(name="Count")
#     )
#     pivot["Label"] = pivot["Fraudulent"].map({0: "Legitimate", 1: "Fraudulent"})
#     fig_prev = px.bar(
#         pivot, x="Previous_Fraudulent_Transactions", y="Count",
#         color="Label", barmode="group",
#         color_discrete_map={"Legitimate": "#2b6cb0", "Fraudulent": "#c53030"},
#         labels={"Previous_Fraudulent_Transactions": "Previous Fraud History (Count)"}
#     )
#     st.plotly_chart(fig_prev, use_container_width=True)
# 
# elif page == "Machine Learning Models":
#     st.title("🤖 Machine Learning Models")
# 
#     st.markdown("""
# > **What are Machine Learning Models?**
# > Smart programs that learn from historical transaction data to distinguish between normal and fraudulent transactions.
# > We train **3 models** and measure their **Accuracy** — the percentage of correct predictions out of all test transactions.
# """)
# 
#     st.divider()
# 
#     X = df_encoded.drop(columns=["Transaction_ID", "User_ID", "Fraudulent"], errors="ignore")
#     y = df_encoded["Fraudulent"]
#     X_train, X_test, y_train, y_test = train_test_split(
#         X, y, test_size=0.20, random_state=42, stratify=y
#     )
# 
#     with st.spinner("⏳ Training models on your real dataset..."):
#         # Scale features — matches notebook pipeline (StandardScaler)
#         scaler = StandardScaler()
#         X_train_sc = scaler.fit_transform(X_train)
#         X_test_sc  = scaler.transform(X_test)
# 
#         # 1. Random Forest — default (no scaling needed for trees, kept for consistency)
#         rf_default = RandomForestClassifier(n_estimators=100, random_state=42)
#         rf_default.fit(X_train, y_train)
#         y_pred_rf = rf_default.predict(X_test)
#         acc_rf = accuracy_score(y_test, y_pred_rf)
#         report_rf = classification_report(y_test, y_pred_rf, target_names=["Normal", "Fraud"], zero_division=0)
# 
#         # 2. Random Forest Balanced + StandardScaler → matches notebook Image 1
#         rf_balanced = RandomForestClassifier(n_estimators=100, random_state=42, class_weight="balanced")
#         rf_balanced.fit(X_train_sc, y_train)
#         y_pred_rf_bal = rf_balanced.predict(X_test_sc)
#         acc_rf_bal = accuracy_score(y_test, y_pred_rf_bal)
#         report_rf_bal = classification_report(y_test, y_pred_rf_bal, target_names=["Normal", "Fraud"], zero_division=0)
#         cm_scaled = confusion_matrix(y_test, y_pred_rf_bal)   # "After StandardScaler"
# 
#         # 3. Decision Tree — default (no scaling)
#         dt_default = DecisionTreeClassifier(random_state=42)
#         dt_default.fit(X_train, y_train)
#         y_pred_dt = dt_default.predict(X_test)
#         acc_dt = accuracy_score(y_test, y_pred_dt)
#         report_dt = classification_report(y_test, y_pred_dt, target_names=["Normal", "Fraud"], zero_division=0)
# 
#         # 4. SMOTE on scaled data + Decision Tree → matches notebook Image 2
#         smote = SMOTE(random_state=42)
#         X_sm, y_sm = smote.fit_resample(X_train_sc, y_train)
#         dt_smote = DecisionTreeClassifier(random_state=42)
#         dt_smote.fit(X_sm, y_sm)
#         y_pred_dt_sm = dt_smote.predict(X_test_sc)
#         acc_dt_sm = accuracy_score(y_test, y_pred_dt_sm)
#         cm_smote = confusion_matrix(y_test, y_pred_dt_sm)   # "SMOTE Model"
# 
#     # ── Section 1: Model Cards ─────────────────────────────────────────────────
#     st.subheader("🧠 Models Used")
# 
#     c1, c2, c3 = st.columns(3)
#     with c1:
#         st.info(f"""
# **🌲 Random Forest**
# Builds hundreds of decision trees and takes the majority vote.
# Strong and reliable in most cases.
# 
# **Accuracy: `{acc_rf*100:.2f}%`**
# """)
#     with c2:
#         st.warning(f"""
# **⚖️ Random Forest (Balanced)**
# Same model but gives extra weight to rare fraud cases during training.
# 
# **Accuracy: `{acc_rf_bal*100:.2f}%`**
# """)
#     with c3:
#         st.success(f"""
# **🌿 Decision Tree**
# Like a flowchart — asks yes/no questions step by step to reach a decision.
# Easy to understand and interpret.
# 
# **Accuracy: `{acc_dt*100:.2f}%`**
# """)
# 
#     st.divider()
# 
#     # ── Section 2: Accuracy Chart ──────────────────────────────────────────────
#     st.subheader("📊 Model Accuracy Comparison")
#     st.caption("Accuracy = % of correct predictions out of 10,000 test transactions")
# 
#     acc_data = pd.DataFrame({
#         "Model": ["Random Forest", "RF Balanced", "Decision Tree"],
#         "Accuracy": [acc_rf*100, acc_rf_bal*100, acc_dt*100]
#     })
#     fig_acc = px.bar(
#         acc_data, x="Model", y="Accuracy",
#         text=[f"{v:.2f}%" for v in acc_data["Accuracy"]],
#         color="Model",
#         color_discrete_sequence=["#2b6cb0", "#d97706", "#2f855a"],
#     )
#     fig_acc.update_traces(textposition="outside", textfont_size=14)
#     fig_acc.update_layout(
#         yaxis_range=[0, 115], showlegend=False,
#         yaxis_title="Accuracy (%)", xaxis_title="",
#         plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)"
#     )
#     st.plotly_chart(fig_acc, use_container_width=True)
# 
#     st.divider()
# 
#     # ── Section 3: Classification Reports ─────────────────────────────────────
#     st.subheader("📋 Classification Reports")
#     st.caption("**Precision** = Of all fraud alerts, how many were real? | **Recall** = Of all real fraud cases, how many did the model catch? | **F1** = Balance between both")
# 
#     t1, t2, t3 = st.tabs(["🌲 Random Forest", "⚖️ RF Balanced", "🌿 Decision Tree"])
#     with t1:
#         st.code(report_rf, language="text")
#     with t2:
#         st.code(report_rf_bal, language="text")
#     with t3:
#         st.code(report_dt, language="text")
# 
#     st.divider()
# 
#     # ── Section 4: SMOTE Before vs After ──────────────────────────────────────
#     st.subheader("🔁 SMOTE Effect — Confusion Matrices")
#     st.markdown("""
# > **What is SMOTE?**
# > A technique that generates synthetic fraud samples during training — because fraud is very rare (~5% only).
# > Here we compare **RF Balanced + StandardScaler** (baseline) vs **Decision Tree + SMOTE + StandardScaler**.
# """)
# 
#     col_b, col_a = st.columns(2)
# 
#     # Exact values from notebook — do not change
#     import numpy as np
#     cm_nb_scaled = np.array([[7339, 2195], [349, 117]])   # After StandardScaler
#     cm_nb_smote  = np.array([[8013, 1521], [391,  75]])   # SMOTE Model
# 
#     with col_b:
#         st.markdown("#### RF Balanced + StandardScaler")
#         tn, fp, fn, tp = 7339, 2195, 349, 117
#         m1, m2 = st.columns(2)
#         m1.metric("Fraud Caught (TP)", tp)
#         m2.metric("Fraud Missed (FN)", fn)
#         m3, m4 = st.columns(2)
#         m3.metric("True Normal (TN)", f"{tn:,}")
#         m4.metric("False Alarm (FP)", f"{fp:,}")
#         fig_b = px.imshow(
#             cm_nb_scaled,
#             text_auto=True,
#             x=["Normal", "Fraud"],
#             y=["Normal", "Fraud"],
#             labels={"x": "Predicted label", "y": "True label"},
#             color_continuous_scale="Blues",
#             title="Confusion Matrix - After apply StandardScaler",
#         )
#         fig_b.update_traces(textfont_size=18)
#         fig_b.update_layout(
#             coloraxis_showscale=True,
#             title_font_size=14,
#             plot_bgcolor="rgba(0,0,0,0)",
#             paper_bgcolor="rgba(0,0,0,0)",
#         )
#         st.plotly_chart(fig_b, use_container_width=True)
# 
#     with col_a:
#         st.markdown("#### Decision Tree + SMOTE")
#         tn2, fp2, fn2, tp2 = 8013, 1521, 391, 75
#         n1, n2 = st.columns(2)
#         n1.metric("Fraud Caught (TP)", tp2, delta=f"{tp2-tp:+d}")
#         n2.metric("Fraud Missed (FN)", fn2, delta=f"{fn2-fn:+d}", delta_color="inverse")
#         n3, n4 = st.columns(2)
#         n3.metric("True Normal (TN)", f"{tn2:,}")
#         n4.metric("False Alarm (FP)", f"{fp2:,}", delta=f"{fp2-fp:+,}", delta_color="inverse")
#         fig_a = px.imshow(
#             cm_nb_smote,
#             text_auto=True,
#             x=["Normal", "Fraud"],
#             y=["Normal", "Fraud"],
#             labels={"x": "Predicted label", "y": "True label"},
#             color_continuous_scale="Blues",
#             title="Confusion Matrix - SMOTE Model",
#         )
#         fig_a.update_traces(textfont_size=18)
#         fig_a.update_layout(
#             coloraxis_showscale=True,
#             title_font_size=14,
#             plot_bgcolor="rgba(0,0,0,0)",
#             paper_bgcolor="rgba(0,0,0,0)",
#         )
#         st.plotly_chart(fig_a, use_container_width=True)
# 
#     st.info(
#         "💡 **Summary:** StandardScaler normalizes the features before training. "
#         "SMOTE generates synthetic fraud samples to help the model learn from rare fraud cases. "
#         "Each model trades off between catching fraud (recall) and avoiding false alarms (precision)."
#     )
# 
#     joblib.dump(rf_default, "fraud_model.pkl")
#     joblib.dump(global_encoders, "encoders.pkl")
#     st.success(f"✅ All models trained and saved. Best accuracy: **Random Forest** at **{acc_rf*100:.2f}%**")
# 
# elif page == "Real-Time Fraud Prediction":
#     st.title("💳 Real-Time Fraud Simulation & Prediction")
#     st.write("Enter transaction details below to predict whether it is fraudulent or legitimate.")
# 
#     try:
#         model = joblib.load("fraud_model.pkl")
#         encoders = joblib.load("encoders.pkl")
#     except FileNotFoundError:
#         st.error(
#             "⚠️ No trained model found. "
#             "Please go to **Machine Learning Models** tab first to train and save the model."
#         )
#         st.stop()
# 
#     st.markdown("### Enter Transaction Parameters")
# 
#     row1_col1, row1_col2, row1_col3 = st.columns(3)
#     with row1_col1:
#         amount = st.number_input(
#             "Transaction Amount ($)",
#             min_value=0.0,
#             max_value=float(df["Transaction_Amount"].max()),
#             value=float(df["Transaction_Amount"].median())
#         )
#     with row1_col2:
#         transaction_type = st.selectbox(
#             "Transaction Type",
#             sorted(df["Transaction_Type"].unique())
#         )
#     with row1_col3:
#         transaction_time = st.selectbox(
#             "Hour of Transaction (0-23)",
#             sorted([int(x) for x in df["Time_of_Transaction"].unique()])
#         )
# 
#     row2_col1, row2_col2, row2_col3 = st.columns(3)
#     with row2_col1:
#         device = st.selectbox("Device Used", sorted(df["Device_Used"].unique()))
#     with row2_col2:
#         location = st.selectbox("Location", sorted(df["Location"].unique()))
#     with row2_col3:
#         payment_method = st.selectbox("Payment Method", sorted(df["Payment_Method"].unique()))
# 
#     row3_col1, row3_col2, row3_col3 = st.columns(3)
#     with row3_col1:
#         prev_fraud = st.selectbox(
#             "Previous Fraudulent Transactions",
#             sorted([int(x) for x in df["Previous_Fraudulent_Transactions"].unique()])
#         )
#     with row3_col2:
#         account_age = st.number_input(
#             "Account Age (Months)",
#             min_value=1,
#             max_value=int(df["Account_Age"].max()),
#             value=int(df["Account_Age"].median())
#         )
#     with row3_col3:
#         num_tx_24h = st.number_input(
#             "Transactions in Last 24H",
#             min_value=1,
#             max_value=int(df["Number_of_Transactions_Last_24H"].max()),
#             value=int(df["Number_of_Transactions_Last_24H"].median())
#         )
# 
#     if st.button("🔍 Analyze & Predict Fraud Status", use_container_width=True, type="primary"):
#         try:
#             enc_type = encoders["Transaction_Type"].transform([transaction_type])[0]
#             enc_device = encoders["Device_Used"].transform([device])[0]
#             enc_location = encoders["Location"].transform([location])[0]
#             enc_payment = encoders["Payment_Method"].transform([payment_method])[0]
# 
#             input_data = pd.DataFrame([{
#                 "Transaction_Amount": amount,
#                 "Transaction_Type": enc_type,
#                 "Time_of_Transaction": transaction_time,
#                 "Device_Used": enc_device,
#                 "Location": enc_location,
#                 "Previous_Fraudulent_Transactions": prev_fraud,
#                 "Account_Age": account_age,
#                 "Number_of_Transactions_Last_24H": num_tx_24h,
#                 "Payment_Method": enc_payment,
#             }])
# 
#             prediction = model.predict(input_data)[0]
#             if hasattr(model, "predict_proba"):
#                 probability = model.predict_proba(input_data)[0][1] * 100
#             else:
#                 probability = 100.0 if prediction == 1 else 0.0
# 
#             st.subheader("📋 Prediction Result")
# 
#             gauge_color = "#c53030" if prediction == 1 else "#276749"
#             fig_gauge = go.Figure(go.Indicator(
#                 mode="gauge+number+delta",
#                 value=probability,
#                 domain={"x": [0, 1], "y": [0, 1]},
#                 title={"text": "Fraud Probability (%)"},
#                 delta={"reference": 50},
#                 gauge={
#                     "axis": {"range": [0, 100]},
#                     "bar": {"color": gauge_color},
#                     "steps": [
#                         {"range": [0, 30], "color": "#c6f6d5"},
#                         {"range": [30, 60], "color": "#fefcbf"},
#                         {"range": [60, 100], "color": "#fed7d7"},
#                     ],
#                     "threshold": {
#                         "line": {"color": "black", "width": 4},
#                         "thickness": 0.75,
#                         "value": 50,
#                     },
#                 },
#             ))
#             st.plotly_chart(fig_gauge, use_container_width=True)
# 
#             if prediction == 1:
#                 st.error(
#                     f"🚨 **HIGH RISK — FRAUDULENT TRANSACTION DETECTED!**\n\n"
#                     f"Fraud Probability: **{probability:.2f}%**"
#                 )
#                 st.warning(
#                     "⚠️ **Recommendation:** Immediately hold this transaction and trigger "
#                     "manual compliance review before proceeding."
#                 )
#             else:
#                 st.success(
#                     f"✅ **LOW RISK — TRANSACTION CLEARED AS LEGITIMATE**\n\n"
#                     f"Fraud Probability: **{probability:.2f}%**"
#                 )
#                 st.info(
#                     "ℹ️ **Recommendation:** Transaction can be processed normally."
#                 )
# 
#             with st.expander("📋 Input Summary"):
#                 input_summary = pd.DataFrame([{
#                     "Transaction Amount ($)": f"${amount:,.2f}",
#                     "Transaction Type": transaction_type,
#                     "Hour": transaction_time,
#                     "Device": device,
#                     "Location": location,
#                     "Payment Method": payment_method,
#                     "Previous Fraud History": prev_fraud,
#                     "Account Age (months)": account_age,
#                     "Transactions Last 24H": num_tx_24h,
#                 }]).T.reset_index()
#                 input_summary.columns = ["Parameter", "Value"]
#                 input_summary["Value"] = input_summary["Value"].astype(str)
#                 st.dataframe(input_summary, use_container_width=True, hide_index=True)
# 
#         except ValueError as e:
#             st.error(
#                 f"⚠️ Encoding error — the value you selected may not exist in the training data. "
#                 f"Details: {e}"
#             )
#






